FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["PawHQ.API/PawHQ.API.csproj", "PawHQ.API/"]
RUN dotnet restore "PawHQ.API/PawHQ.API.csproj"

COPY . .

WORKDIR "/src/PawHQ.API"
RUN dotnet build "PawHQ.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PawHQ.API.dll"]